### ISSUE TITLE
Wrap children around the element passed through props, defaults to div if no element is specified

### ISSUE THREAD

**Issue by calebdeji** [ooade/react-click-away-listener#15]
Currently, children are wrapped around div. We should be able to specify the element to wrap the children. I have submitted a PR if you think this is valid

**Comment by calebdeji** [comment]
https://github.com/ooade/react-click-away-listener/pull/14

**Comment by ooade** [comment]
Closed in https://github.com/ooade/react-click-away-listener/pull/14
