### ISSUE TITLE
Portal

### ISSUE THREAD

**Issue by hatpick** [ooade/react-click-away-listener#19]
Do you have any plans for supporting portals?

**Comment by ooade** [comment]
Hi there! Apologies for just replying.

I'm not sure what you mean but it works in a Portal. Here's [an example](https://codesandbox.io/s/beautiful-mirzakhani-q0ufm?file=/src/App.js).

Maybe you can share what you really want to achieve and I'll be able to answer appropriately.

**Comment by hatpick** [comment]
@ooade Thanks for the reply.

The code snippet you have above is having the ClickAway component within the Modal. I'm talking about a case such as this:
```
<ClickAway>
   ...stuff...
   <Portal>...</Portal>
</ClickAway>
```

**Comment by ooade** [comment]
Oh. I'm not sure we are going to support that.

**Comment by hatpick** [comment]
You should be able to achieve that via React synthetic events, Portal bubbles up click events to the parent component in React.

**Comment by ooade** [comment]
We can actually support it. I didn't just think a lot of people would need it. I'll implement it later today 🙏

**Comment by ooade** [comment]
I just published a beta package that supports it @hatpick. Can you try it out and give feedback?

Install:
```
yarn add react-click-away-listener@beta
```

**Comment by hatpick** [comment]
https://codesandbox.io/s/pedantic-nightingale-k20jp
Start typing = in the textbox to get a portal context menu, each sub menu is a new portal.
(check console for "away" messages)

It seems like it's working even without isPortal props.

**Comment by ooade** [comment]
Yeah, it'll work but not work as expected if not passed.

**Comment by ooade** [comment]
Hi @hatpick Does it work at expected? If it doesn't, what's the expected behaviour?

**Comment by hatpick** [comment]
In my demo, I was using material core clickaway listener, I replaced it with yours and it seems identical, so I can only assume that it works as expected. :) good job.

**Comment by ooade** [comment]
Good to know. Thanks a lot! 🕺

**Comment by oliviertassinari** [comment]
> I was using material core clickaway listener, I replaced it with yours

@hatpick Why? :)
