### ISSUE TITLE
Doesn't trigger with right click

### ISSUE THREAD

**Issue by JohannesKlauss** [ooade/react-click-away-listener#34]
Is there a way to add a flag that also right click events should trigger the clickAway handler?

**Comment by ooade** [comment]
Hi @JohannesKlauss, you can pass in `mousedown` to `mouseEvent` and that would trigger the ClickAway handler to run as soon as the mouse is pressed.

**Comment by JohannesKlauss** [comment]
Works like a charm, thank you :)
