### ISSUE TITLE
Click away listener not working the same on React 17

### ISSUE THREAD

**Issue by zenstok** [ooade/react-click-away-listener#35]
I've updated from React 16.14.0 to React 17.0.2 and now it seems like click event listener component triggers whenever it's mounted. This made a component i created no longer work.

Can you check this?

**Comment by ooade** [comment]
@zenstok What version of the Clickaway listener are you using?

**Comment by zenstok** [comment]
@ooade i'm using version 2.0.0

```
react-click-away-listener@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/react-click-away-listener/-/react-click-away-listener-2.0.0.tgz#b70e4b87f8529fef2ce658469f415f15fc689c83"
  integrity sha512-tD32K4usq0v+JWgeP+8B2B84rSR8Gcvs92cnBvlZkkBrgjVWetQUuMCN7De3vyZ36UcOG97JOvWGevyTMEHtdw==
```

**Comment by ooade** [comment]
Thanks. 

I just updated the dependencies on [the example](https://codesandbox.io/s/52384lyo8p) and it works fine. Can you perhaps help recreate this on CodeSandbox and share? I'd appreciate that. 🙏

**Comment by zenstok** [comment]
https://codesandbox.io/s/clickawaylistener-example-forked-uch2g?file=/src/index.js

Above you have an example when it's not working. I figured it out and it looks like it doesn't work if i have a `<Menu/>`component with keepsMounted prop set to true. 

Below you have the exact same code but with React version set to 16.14.0 and this one works.

https://codesandbox.io/s/clickawaylistener-example-forked-q7nz2?file=/src/index.js

**Comment by ooade** [comment]
This has been fixed in the latest version. 

Thanks a lot for reporting and taking the time to create an example on CodeSandbox 🙏
