### ISSUE TITLE
Click inside of div on react-icons icon calls OnClickAway

### ISSUE THREAD

**Issue by TGChrisRArendt** [ooade/react-click-away-listener#45]
![image](https://user-images.githubusercontent.com/47191729/128374660-299f9a6c-3fee-406b-bdd8-f538ca307ad5.png)
When I click on these items, the popup is closed, but it shouldn't be. For example if I click on the embed code copy button then the menu should remain open.

```
<ClickAwayListener onClickAway={() => mapDetailsOpen && setMapDetailsOpen(false)}>
  <div></div>
</ClickAwayListener/>
```
Using the latest pre-react 17 version that I could find, 1.4.4.

**Comment by ooade** [comment]
Is this menu created with a portal? If yes, we only fixed the issues with portals after this version 😿

**Comment by TGChrisRArendt** [comment]
Yes :(

**Comment by TGChrisRArendt** [comment]
Actually, I fixed my issue. I had created the popup in a map:

```
{things.map(thing=>(
<ClickAwayListener onClickAway={() => mapDetailsOpen && setMapDetailsOpen(false)}>
  <div>Menu stuff</div>
</ClickAwayListener/>
)}
```

So when one of the items was clicked outside of (which happens when you click inside of one of the menus because its not another menu, and that menu is triggered) then it would close the menu. So I had to add a condition that we would only consider "this" dropdown's related map objectId (which is what i'm using to figure out which dropdown is open / close the others):

```
{things.map(thing=>(
<ClickAwayListener onClickAway={() => reactMap.map.objectId === mapDetailsOpen && setMapDetailsOpen(false)}>
  <div>Menu stuff</div>
</ClickAwayListener/>
)}
```

I tried to do it like this but it doesn't work when I click on my embed copy button, it just closes:

```
const [isOpen, setIsOpen] = React.useState(false);
<ClickAwayListener onClickAway={event => isOpen && setIsOpen(false)}>...</ClickAwayListener >
```

**Comment by TGChrisRArendt** [comment]
The problem I'm having is caused by clicking on a `react-icons` icon. I added the text "copy" to the embed part of the popup, and clicking on the text doesn't close the popup but clicking on the icon closes it.

**Comment by ooade** [comment]
Hi. You're permitted to copy the code here in your project and use it with your version of React. You would also need to call `event.persist` in handleEvents.
