### ISSUE TITLE
Could not resolve dependency: npm ERR! peer react@"^17.0.2" from react-click-away-listener@2.1.0

### ISSUE THREAD

**Issue by JaredDahlke** [ooade/react-click-away-listener#58]
does not work with react 18 ?

**Comment by ooade** [comment]
Sorry, not yet. I'll integrate with React 18 once I've tested it extensively as there are some types related [issues](https://github.com/facebook/react/issues/24304) at the moment.

**Comment by ooade** [comment]
Upgraded in #59
