### ISSUE TITLE
an error appear in console when you add touchEvent

### ISSUE THREAD

**Issue by Revan99** [ooade/react-click-away-listener#60]
**Describe the bug**
the bug is some error appear in console when you add touchEvent

**To Reproduce**
5. 
![image](https://user-images.githubusercontent.com/46955286/163768015-b16540b6-a184-4837-bd36-bb1713e71b0e.png)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46955286/163768035-4f9b8c44-9946-42e3-ae7a-0a0882ba10ee.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 100

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ooade** [comment]
Sorry, I have a few questions:
- Are you wrapping the click away listener around `AyncRadioDropdown`?
- If yes, do you have the ref forwarded in AsyncRadioDropdown?

**Comment by ooade** [comment]
Hi there, does this issue still exists?
