### ISSUE TITLE
v2.2.0 introduced a breaking change by dropping React 17 support

### ISSUE THREAD

**Issue by wojtekmaj** [ooade/react-click-away-listener#61]
**Describe the bug**

In #59 a change has been introduced that changes `peerDependencies` of `react` and `react-dom` to only allow versions `^18.0.0`. This introduced a breaking change by dropping support for React 17.

I suggest setting peerDependencies to `^17.0.0 || ^18.0.0` to fix a breaking change.

And actually, while we're at it, it looks like your code should run perfectly in ^16.8.0 as well. So perhaps even set it to `^16.8.0 || ^17.0.0 || ^18.0.0`?

**Comment by ooade** [comment]
Thanks! I'll create a PR to add support for them.
