### ISSUE TITLE
Let click-away event do not report if we click / focus the children of the element.

### ISSUE THREAD

**Issue by PeterlitsZo** [ooade/react-click-away-listener#63]
**Describe the bug**
1. When I click a button, the website will show me a list. And it uses `react-click-away-listener`.
2. I want to choose one clickable element by my `Tab` key.
3. Ok. Now I choose it - a child of the list.
4. Oh no. The list get the click-away event and close itself - and its children.

**To Reproduce**
:eyes:

**Expected behavior**
I hope if I try to focus the children, (even click the children), it will never get the click-away event.

**Screenshots**
:eyes:

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Firefox
 - Version 99.0.1

**Smartphone (please complete the following information):**
:eyes:

**Additional context**
I try to use `focusEvent="none"` to disable. It works now. But not good.

**Comment by PeterlitsZo** [comment]
I am not sure what happened. But when I try to use code below, I cannot get the same result:

```typescript
import React, { useRef, forwardRef } from 'react';
import ReactDOM from 'react-dom';
import ClickAwayListerner from 'react-click-away-listener';

interface ModalProps extends React.HTMLAttributes<HTMLDivElement> {
  onClickAway?: React.ComponentProps<typeof ClickAwayListerner>['onClickAway'];
};

const Modal = forwardRef((props: ModalProps, ref: React.Ref<HTMLDivElement>) => {
  const modalRoot = document.getElementById('modal');
  let { onClickAway = () => null, ...otherProps } = props;
  const myRef = useRef<HTMLDivElement | null>(null);

  const betterOnClickAway: typeof onClickAway = (event) => {
    console.log(event);
    if (!myRef.current) return;
    onClickAway(event);
  }

  // See: https://stackoverflow.com/a/62238917/13031497
  return ReactDOM.createPortal(
    <ClickAwayListerner onClickAway={onClickAway}>
      <div
        ref={(node) => {
          myRef.current = node;
          if (typeof ref === 'function') {
            ref(node);
          } else if (ref && node) {
            (ref as React.MutableRefObject<HTMLDivElement>).current = node;
          }
        }}
        {...otherProps}
      />
    </ClickAwayListerner>,
    modalRoot!
  );
});

export default Modal;
```

Need I close this issue?

**Comment by ooade** [comment]
In case it resurfaces, please let me know.
