### ISSUE TITLE
Click on iframe elements doesn't trigger listener

### ISSUE THREAD

**Issue by olga-gchak** [ooade/react-click-away-listener#64]
When we "add react-click-away-listener" to some element on page and have some iframe on this page, after click on iframe - listener doesn't triggered.

**Comment by ooade** [comment]
Hi @olga-gchak, sorry for the late response. We currently don't support click away events on an iframe. We should add support for this request soon 🙏

**Comment by olga-gchak** [comment]
Thanks for response. 
It would be great.
