### ISSUE TITLE
OnClickAway trigger when I switch browser tab

### ISSUE THREAD

**Issue by imyanglu** [ooade/react-click-away-listener#68]
**Describe the bug**

**To Reproduce**
1. switch tab
2. back to current tab 
3. onClickAway triggerd

**Expected behavior**
onClickAway  not trigger

Chrome

**Comment by ooade** [comment]
Hi @imyanglu, what version of the library are you using? Because I tried switching tabs on the [example application](https://codesandbox.io/s/52384lyo8p?file=/src/index.js), and it worked fine.

**Comment by imyanglu** [comment]
> Hi @imyanglu, what version of the library are you using? Because I tried switching tabs on the [example application](https://codesandbox.io/s/52384lyo8p?file=/src/index.js), and it worked fine.

it's 2.2.1

**Comment by ooade** [comment]
> > Hi @imyanglu, what version of the library are you using? Because I tried switching tabs on the [example application](https://codesandbox.io/s/52384lyo8p?file=/src/index.js), and it worked fine.
> 
> it's 2.2.1

I'd be glad if you can create an example that mirrors what you have because I can't seem to reproduce it.
