### ISSUE TITLE
v1.1.0 does not appear to be passing Event

### ISSUE THREAD

**Issue by Naismith** [ooade/react-click-away-listener#9]
Hi Again!

v1.1.0 does not appear to be passing the event to the onClickAway function. I copied the source to my application and it seems to be fine. I'm wondering if perhaps there was an issue with the build process. I do have the updates types!

Would you be able to take a look into this?

**Comment by ooade** [comment]
I'll look into it.

**Comment by ooade** [comment]
Works fine here https://codesandbox.io/s/serverless-shadow-xomvc?file=/src/App.js

<img width="1020" alt="Screenshot 2020-05-08 at 20 10 41" src="https://user-images.githubusercontent.com/11811904/81440492-0da89600-9168-11ea-86e2-80ffeb3f0a71.png">

**Comment by Naismith** [comment]
Interesting - wondering if NPM is caching something. I'll take a look!
